name: Playwright API Tests with Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: write



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start API with Docker
        run: |
          docker run -d --name user-api -p 3000:3000 ghcr.io/danielsilva-loanpro/sdet-interview-challenge:latest

      - name: Verify Container
        run: docker ps -a

      - name: Wait for API
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:3000/dev/users; then
              echo "API is ready"
              exit 0
            fi
            echo "Waiting for API..."
            sleep 3
          done
          echo "API failed to start"

          echo "===== CONTAINER LOGS =====" 
          docker logs user-api

          exit 1

      - name: Configure Environment Variables
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment }}"

          if [ -z "$ENVIRONMENT" ]; then
            ENVIRONMENT="dev"
          fi

          echo "TEST_ENV=$ENVIRONMENT" >> $GITHUB_ENV
          echo "BASE_URL=http://localhost:3000/$ENVIRONMENT/" >> $GITHUB_ENV
          echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> $GITHUB_ENV

      - name: Display Environment
        run: |
          echo "Running tests against:"
          echo "TEST_ENV=$TEST_ENV" 
          echo "BASE_URL=$BASE_URL"

      - name: Validate Environment Endpoint 
        run: | 
              echo "Checking endpoint..." 
              curl -v $BASE_URL/users

      - name: Show container logs
        if: always()
        run: |
              docker ps -a
              docker logs $(docker ps -q)

      - name: Test POST manually
        run: |
          curl -X POST \
          http://localhost:3000/dev/users \
          -H "Content-Type: application/json" \
          -d '{"name":"Test User","email":"test@mail.com","age":30}'

      - name: Execute Playwright Tests
        run: npx playwright test

      - name: Display Docker Logs on Failure 
        if: failure() 
        run: | 
          echo "===== CONTAINER LOGS =====" 
          docker logs user-api

      - name: Show Docker Logs
        if: always()
        run: |
          docker ps -a
          docker logs $(docker ps -q)

      - name: Verify Allure Results
        if: always()
        run: |
          ls -la
          ls -la allure-results || mkdir -p allure-results

      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report